import numpy as np

params = {
    "isoradial_angular_parameters": {
        "start_angle": 0,
        "end_angle": np.pi,
        "angular_precision": 100,
        "mirror": True,
    },
    "isoradial_solver_parameters": {
        "initial_guesses": 12,
        "midpoint_iterations": 20,
        "plot_inbetween": False,
        "min_periastron": 3.001,
        "use_ellipse": True,
    },
    "isoredshift_solver_parameters": {
        "initial_guesses": 12,
        "midpoint_iterations": 12,
        "times_inbetween": 2,
        "retry_angular_precision": 15,
        "min_periastron": 3.01,
        "use_ellipse": True,
        "retry_tip": 50,
        "initial_radial_precision": 15,
        "plot_inbetween": False,
    },
    "plot_params": {
        "plot_isoredshifts_inbetween": True,
        "save_plot": True,
        "plot_ellipse": True,
        "plot_core": True,
        "redshift": True,
        "linestyle": "dashed",
        "linewidth": 1.0,
        "key": "",
        "face_color": "black",
        "line_color": "white",
        "text_color": "white",
        "alpha": 1.0,
        "show_grid": False,
        "legend": True,
        "orig_background": False,
        "plot_disk_edges": True,
        "ax_lim": [-100, 100],
    },
}
